version: "3.4"

services:
  onlyoffice-connector:
    image: twakedrive/onlyoffice-connector:latest
    environment:
      - SERVER_PORT=5000
      - SERVER_PREFIX=/plugins/onlyoffice/
      - CREDENTIALS_ENDPOINT=http://localhost:4000/
      - ONLY_OFFICE_SERVER=http://localhost:8090/
      - CREDENTIALS_ID=tdrive_onlyoffice
      - CREDENTIALS_SECRET=c1cc66db78e1d3bb4713c55d5ab2
      - SERVER_ORIGIN=http://192.168.6.138:5000
    network_mode: host

networks:
  tdrive_network:
    name: tdrive_tdrive_network
    external: true
