version: "3.4"

services:
  onlyoffice-connector:
    image: twakedrive/onlyoffice-connector:latest
    environment:
      - SERVER_PORT=5000
      - SERVER_PREFIX=/plugins/onlyoffice/
      - SERVER_ORIGIN=https://connector.rdrive.test.jules.ryvie.fr
      - CREDENTIALS_ENDPOINT=https://backend.rdrive.test.jules.ryvie.fr/
      - ONLY_OFFICE_SERVER=https://document.rdrive.test.jules.ryvie.fr/
      - CREDENTIALS_ID=tdrive_onlyoffice
      - CREDENTIALS_SECRET=c1cc66db78e1d3bb4713c55d5ab2
    # Utiliser le même mode réseau que dans le fichier original
    network_mode: host
    restart: unless-stopped
